### ISSUE TITLE
iOS 64-bit Support problem

### ISSUE THREAD

**Issue by bau720123** [Wizcorp/phonegap-plugin-wizUtils#13]
according to this
http://phonegap.com/blog/2015/01/20/ios-64bit-support/
this plugin will install fail by PGB (build.phonegap.com) for now

**Comment by aogilvie** [comment]
This plugin has not been updated for quite a while but it is compatible with 64bit iOS devices. The sample projects however, may not work because the samples use an old version of Cordova.

**Comment by bau720123** [comment]
got it~
hope one day this plugin can update to a new cordova version

**Comment by bau720123** [comment]
hi @aogilvie 
just feedback some information
when I use phonegap build 3.7
it will alert this warning in iOS

Check dependencies
warning: no rule to process file '/project/jQuerytestMobileforPhoneGapEdition/Plugins/jp.wizcorp.phonegap.plugin.wizUtilsPlugin/WizDebugLog.h' of type sourcecode.c.h for architecture armv7
warning: no rule to process file '/project/jQuerytestMobileforPhoneGapEdition/Plugins/jp.wizcorp.phonegap.plugin.wizUtilsPlugin/WizDebugLog.h' of type sourcecode.c.h for architecture arm64
